package com.example.pdm2_projeto.models;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a user account entity stored in a Room database.
 * This entity keeps track of the last login timestamp for an account.
 */
@Entity(tableName = "account")
public class Account {

    /**
     * Unique identifier for each account entry in the database.
     * Auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;

    /**
     * Stores the timestamp of the last login.
     */
    private long lastLoginTimestamp;

    /**
     * Constructor to create an Account object with a given last login timestamp.
     *
     * @param lastLoginTimestamp The timestamp of the last login.
     */
    public Account(long lastLoginTimestamp) {
        this.lastLoginTimestamp = lastLoginTimestamp;
    }

    /**
     * Gets the unique ID of the account.
     *
     * @return The account ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the account.
     * This is primarily used by Room for auto-generation purposes.
     *
     * @param id The account ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the last login timestamp of the account.
     *
     * @return The timestamp representing the last login time.
     */
    public long getLastLoginTimestamp() {
        return lastLoginTimestamp;
    }

    /**
     * Updates the last login timestamp.
     *
     * @param lastLoginTimestamp The new last login timestamp.
     */
    public void setLastLoginTimestamp(long lastLoginTimestamp) {
        this.lastLoginTimestamp = lastLoginTimestamp;
    }
}

